#!/usr/bin/env bash
# Gemini CLI Adapter — translates universal config into Gemini CLI format
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"
GEMINI_HOME="$HOME/.gemini"

install() {
  echo "  Installing Gemini CLI configuration..."

  mkdir -p "$GEMINI_HOME"

  # Generate GEMINI.md from universal rules and commands
  {
    echo "# Global Instructions for Gemini CLI"
    echo "> Auto-generated by claude-auto-setup. Do not edit directly."
    echo "> Source: universal/rules/ + universal/commands/"
    echo ""

    echo "## Core Rules"
    echo ""
    echo "### Code Quality"
    cat "$UNIVERSAL_DIR/rules/code-quality.md" | grep -v "^#"
    echo ""

    echo "### Security"
    cat "$UNIVERSAL_DIR/rules/security.md" | grep -v "^#"
    echo ""

    echo "### Testing"
    cat "$UNIVERSAL_DIR/rules/testing.md" | grep -v "^#"
    echo ""

    echo "### Git Workflow"
    cat "$UNIVERSAL_DIR/rules/git-workflow.md" | grep -v "^#"
    echo ""

    echo "## Orchestration Protocol"
    echo ""
    echo "When asked to implement a feature, follow this workflow:"
    echo "1. Explore: understand existing code patterns before changing anything"
    echo "2. Plan: create a spec with clear tasks and wait for approval"
    echo "3. Implement: make changes following existing patterns"
    echo "4. Review: check code quality, security, performance"
    echo "5. Verify: run build, tests, lint — confirm all pass"
    echo ""

    echo "## Available Roles"
    echo "When asked which role to operate in:"
    echo "- Developer: plan and implement directly"
    echo "- Coordinator: plan and delegate to sub-tasks"
    echo "- Reviewer: review code for quality, security, performance"
    echo ""

    echo "## Project Intelligence"
    echo "If a file named .ai/project-intel.md exists, read it first."
    echo "It contains a cached codebase map (architecture, APIs, models, patterns)."
    echo "Use it to avoid re-exploring known areas."
  } > "$GEMINI_HOME/GEMINI.md"

  echo "    GEMINI.md: generated ($(wc -l < "$GEMINI_HOME/GEMINI.md") lines)"

  # Merge MCP servers into settings if settings exist
  if [ -f "$GEMINI_HOME/settings.json" ]; then
    echo "    Settings: existing settings preserved"
  else
    echo '{}' > "$GEMINI_HOME/settings.json"
    echo "    Settings: initialized"
  fi
}

uninstall() {
  echo "  Uninstalling Gemini CLI configuration..."
  [ -f "$GEMINI_HOME/GEMINI.md" ] && rm "$GEMINI_HOME/GEMINI.md" && echo "    GEMINI.md: removed"
}

"$@"
