#!/usr/bin/env bash
# Amp Code Adapter — translates universal config into Amp format
#
# Amp uses:
#   AGENTS.md              — project-level instructions (like CLAUDE.md)
#   .agents/skills/        — specialized skills (like .claude/commands/)
#   .agents/checks/        — code review invariants (like rules)
#   ~/.config/agents/skills/ — global user skills
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"
AMP_HOME="$HOME/.config/agents"

install() {
  echo "  Installing Amp Code configuration..."

  # --- Global skills (~/.config/agents/skills/) ---
  mkdir -p "$AMP_HOME/skills"

  # Convert universal commands to Amp skills format
  # Each skill is a directory with SKILL.md
  local count=0
  for f in "$UNIVERSAL_DIR/commands/"*.md; do
    local name
    name=$(basename "$f" .md)
    local skill_dir="$AMP_HOME/skills/$name"
    mkdir -p "$skill_dir"

    # Extract first line as description, rest as body
    local desc
    desc=$(head -1 "$f" | sed 's/^#\s*//')

    {
      echo "---"
      echo "name: $name"
      echo "description: $desc"
      echo "---"
      echo ""
      # Skip the first heading line, include rest
      tail -n +2 "$f"
    } > "$skill_dir/SKILL.md"

    count=$((count + 1))
  done
  echo "    Skills: $count installed to ~/.config/agents/skills/"

  # --- Global checks (~/.config/agents/checks/) ---
  mkdir -p "$AMP_HOME/checks"

  # Convert universal rules to Amp checks format
  for f in "$UNIVERSAL_DIR/rules/code-quality.md" "$UNIVERSAL_DIR/rules/security.md" "$UNIVERSAL_DIR/rules/testing.md"; do
    if [ -f "$f" ]; then
      local name
      name=$(basename "$f" .md)
      local desc
      desc=$(head -1 "$f" | sed 's/^#\s*//')

      {
        echo "---"
        echo "name: $name"
        echo "description: $desc"
        echo "---"
        echo ""
        tail -n +2 "$f"
      } > "$AMP_HOME/checks/$name.md"
    fi
  done
  echo "    Checks: $(ls "$AMP_HOME/checks/"*.md 2>/dev/null | wc -l) installed"

  # --- Generate global AGENTS.md template ---
  {
    echo "# Global Agent Instructions"
    echo "> Auto-generated by claude-auto-setup."
    echo ""
    echo "## Core Rules"
    echo ""
    echo "### Code Quality"
    cat "$UNIVERSAL_DIR/rules/code-quality.md" | grep -v "^#"
    echo ""
    echo "### Security"
    cat "$UNIVERSAL_DIR/rules/security.md" | grep -v "^#"
    echo ""
    echo "### Testing"
    cat "$UNIVERSAL_DIR/rules/testing.md" | grep -v "^#"
    echo ""
    echo "### Git Workflow"
    cat "$UNIVERSAL_DIR/rules/git-workflow.md" | grep -v "^#"
    echo ""
    echo "## Workflow Protocol"
    echo ""
    echo "When asked to implement a feature:"
    echo "1. Read .ai/project-intel.md if it exists (cached codebase knowledge)"
    echo "2. Explore the relevant files before making changes"
    echo "3. Create a plan and wait for approval"
    echo "4. Implement following existing patterns"
    echo "5. Run build + tests + lint to verify"
    echo "6. Review for quality and security before delivering"
    echo ""
    echo "## Project Intelligence"
    echo "If .ai/project-intel.md exists in the project, read it first."
    echo "It contains a cached codebase map with architecture, APIs, data models,"
    echo "patterns, dependencies, and critical paths."
  } > "$AMP_HOME/AGENTS.md"

  echo "    AGENTS.md: generated ($(wc -l < "$AMP_HOME/AGENTS.md") lines)"
}

uninstall() {
  echo "  Uninstalling Amp Code configuration..."
  # Only remove auto-generated skills (check for our marker)
  if [ -d "$AMP_HOME/skills" ]; then
    # Remove skills that match our universal commands
    for f in "$UNIVERSAL_DIR/commands/"*.md; do
      local name
      name=$(basename "$f" .md)
      rm -rf "$AMP_HOME/skills/$name" 2>/dev/null
    done
    echo "    Skills: removed"
  fi
  [ -d "$AMP_HOME/checks" ] && rm -rf "$AMP_HOME/checks" && echo "    Checks: removed"
  [ -f "$AMP_HOME/AGENTS.md" ] && rm "$AMP_HOME/AGENTS.md" && echo "    AGENTS.md: removed"
}

"$@"
