#!/usr/bin/env bash
# Kiro CLI Adapter — translates universal config into Kiro CLI format
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"
KIRO_HOME="$HOME/.kiro"

install() {
  echo "  Installing Kiro CLI configuration..."

  mkdir -p "$KIRO_HOME/steering"

  # Kiro uses "steering files" — similar to rules
  for f in "$UNIVERSAL_DIR/rules/"*.md; do
    local name
    name=$(basename "$f")
    \cp -f "$f" "$KIRO_HOME/steering/$name"
  done
  echo "    Steering files: $(ls "$KIRO_HOME/steering/"*.md 2>/dev/null | wc -l) installed"

  # Generate main steering file with orchestration instructions
  {
    echo "# Kiro Global Steering"
    echo "> Auto-generated by claude-auto-setup."
    echo ""
    echo "## Workflow Protocol"
    echo ""
    echo "When asked to implement any feature:"
    echo "1. Read .ai/project-intel.md if it exists (cached codebase knowledge)"
    echo "2. Explore the relevant files before making changes"
    echo "3. Create a plan and wait for approval"
    echo "4. Implement following existing code patterns"
    echo "5. Run build + tests + lint to verify"
    echo ""
    echo "## Quality Standards"
    echo "- Match existing code patterns before introducing new ones"
    echo "- Write tests for new functionality"
    echo "- Validate input at system boundaries"
    echo "- Never hardcode secrets or credentials"
    echo "- Use descriptive names, early returns, minimal nesting"
    echo ""
    echo "## Git Conventions"
    echo "- Commit format: <type>: <description> (feat, fix, refactor, test, docs)"
    echo "- Keep PRs focused — one feature or fix per PR"
    echo "- Review diff before committing"
  } > "$KIRO_HOME/steering/global.md"

  echo "    Global steering: generated"

  # Initialize config if not exists
  if [ ! -f "$KIRO_HOME/config.json" ]; then
    echo '{}' > "$KIRO_HOME/config.json"
    echo "    Config: initialized"
  else
    echo "    Config: existing config preserved"
  fi
}

uninstall() {
  echo "  Uninstalling Kiro CLI configuration..."
  rm -rf "$KIRO_HOME/steering"
  echo "    Steering files: removed"
}

"$@"
