#!/usr/bin/env bash
# GitHub Copilot CLI Adapter — translates universal config into Copilot CLI format
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"
COPILOT_HOME="$HOME/.copilot"

install() {
  echo "  Installing GitHub Copilot CLI configuration..."

  mkdir -p "$COPILOT_HOME/instructions"

  # Copy universal rules as instruction files
  for f in "$UNIVERSAL_DIR/rules/"*.md; do
    local name
    name=$(basename "$f")
    \cp -f "$f" "$COPILOT_HOME/instructions/$name"
  done
  echo "    Instruction files: $(ls "$COPILOT_HOME/instructions/"*.md 2>/dev/null | wc -l) installed"

  # Generate main instructions file with orchestration workflow
  {
    echo "# Copilot Global Instructions"
    echo "> Auto-generated by claude-auto-setup."
    echo ""
    echo "## Workflow Protocol"
    echo ""
    echo "When asked to implement any feature:"
    echo "1. Read .ai/project-intel.md if it exists (cached codebase knowledge)"
    echo "2. Explore the relevant files before making changes"
    echo "3. Create a plan and wait for approval"
    echo "4. Implement following existing code patterns"
    echo "5. Run build + tests + lint to verify"
    echo ""
    echo "## Quality Standards"
    echo "- Match existing code patterns before introducing new ones"
    echo "- Write tests for new functionality"
    echo "- Validate input at system boundaries"
    echo "- Never hardcode secrets or credentials"
    echo "- Use descriptive names, early returns, minimal nesting"
    echo ""
    echo "## Git Conventions"
    echo "- Commit format: <type>: <description> (feat, fix, refactor, test, docs)"
    echo "- Keep PRs focused — one feature or fix per PR"
    echo "- Review diff before committing"
  } > "$COPILOT_HOME/instructions/global.md"

  echo "    Global instructions: generated"

  # Initialize config if not exists
  if [ ! -f "$COPILOT_HOME/config.json" ]; then
    echo '{}' > "$COPILOT_HOME/config.json"
    echo "    Config: initialized"
  else
    echo "    Config: existing config preserved"
  fi
}

uninstall() {
  echo "  Uninstalling GitHub Copilot CLI configuration..."
  rm -rf "$COPILOT_HOME/instructions"
  echo "    Instruction files: removed"
}

"$@"
