#!/usr/bin/env bash
# OpenAI Codex CLI Adapter — translates universal config into Codex format
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"
CODEX_HOME="$HOME/.codex"

install() {
  echo "  Installing Codex CLI configuration..."

  mkdir -p "$CODEX_HOME"

  # Codex uses AGENTS.md (project-level) and instructions.md (global)
  {
    echo "# Global Instructions for Codex CLI"
    echo "> Auto-generated by claude-auto-setup."
    echo ""

    echo "## Core Rules"
    echo ""
    for f in "$UNIVERSAL_DIR/rules/code-quality.md" "$UNIVERSAL_DIR/rules/security.md" "$UNIVERSAL_DIR/rules/testing.md" "$UNIVERSAL_DIR/rules/git-workflow.md"; do
      if [ -f "$f" ]; then
        cat "$f"
        echo ""
      fi
    done

    echo "## Workflow"
    echo ""
    echo "For any implementation task:"
    echo "1. Read .ai/project-intel.md if it exists (cached codebase map)"
    echo "2. Understand existing patterns before changing code"
    echo "3. Plan the changes and confirm with the user"
    echo "4. Implement with minimal, focused changes"
    echo "5. Write or update tests"
    echo "6. Verify: build passes, tests pass, lint clean"
    echo ""

    echo "## Roles"
    echo "- Developer: plan and implement directly"
    echo "- Reviewer: review for quality, security, performance, architecture"
    echo "- Debugger: investigate, diagnose, fix, verify"
  } > "$CODEX_HOME/instructions.md"

  echo "    instructions.md: generated ($(wc -l < "$CODEX_HOME/instructions.md") lines)"

  # Initialize config.toml if not exists
  if [ ! -f "$CODEX_HOME/config.toml" ]; then
    cat > "$CODEX_HOME/config.toml" << 'TOML'
# Codex CLI configuration
# Auto-generated by claude-auto-setup

[model]
default = "o3"

[approvals]
# Require approval for file writes and shell commands
auto_approve = ["read", "search"]
TOML
    echo "    config.toml: initialized"
  else
    echo "    config.toml: existing config preserved"
  fi
}

uninstall() {
  echo "  Uninstalling Codex CLI configuration..."
  [ -f "$CODEX_HOME/instructions.md" ] && rm "$CODEX_HOME/instructions.md" && echo "    instructions.md: removed"
}

"$@"
