#!/usr/bin/env bash
# Cursor Adapter — translates universal config into Cursor rules format
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
UNIVERSAL_DIR="$REPO_DIR/universal"

# Cursor uses per-project .cursor/rules/ — this generates a global .cursorrules template
install() {
  echo "  Installing Cursor configuration..."

  # Cursor global rules go in home directory
  {
    echo "# Global Cursor Rules"
    echo "# Auto-generated by claude-auto-setup."
    echo ""

    for f in "$UNIVERSAL_DIR/rules/code-quality.md" "$UNIVERSAL_DIR/rules/security.md" "$UNIVERSAL_DIR/rules/testing.md" "$UNIVERSAL_DIR/rules/git-workflow.md"; do
      if [ -f "$f" ]; then
        cat "$f"
        echo ""
      fi
    done

    echo "## Workflow"
    echo ""
    echo "For any implementation task:"
    echo "1. Read .ai/project-intel.md if it exists (cached codebase map)"
    echo "2. Understand existing patterns before changing code"
    echo "3. Plan the changes and confirm with the user"
    echo "4. Implement with minimal, focused changes"
    echo "5. Write or update tests"
    echo "6. Verify: build passes, tests pass, lint clean"
  } > "$HOME/.cursorrules"

  echo "    ~/.cursorrules: generated ($(wc -l < "$HOME/.cursorrules") lines)"
}

uninstall() {
  echo "  Uninstalling Cursor configuration..."
  [ -f "$HOME/.cursorrules" ] && rm "$HOME/.cursorrules" && echo "    ~/.cursorrules: removed"
}

"$@"
